
################### English Navigation ########################
[[main]]
name = "about"
url = "#about"
weight = 1

[[main]]
name = "services"
url = "#services"
weight = 2

[[main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[main]]
name = "team"
url = "#team"
weight = 4

[[main]]
name = "pricing"
url = "#pricing"
weight = 5

[[main]]
name = "blog"
url = "#blog"
weight = 6

[[main]]
name = "contact"
url = "#contact"
weight = 7


[[main]]
name = "Shop"
weight = 7
hasChildren = true

[[main]]
parent = "Shop"
name = "Flora"
url = "#"
weight = 1

[[main]]
parent = "Shop"
name = "Fauna"
url = "#"
weight = 2

[[main]]
name = "DMo"
url = "/"
weight = 8

